{% set name = "opentelemetry-exporter-jaeger" %}
{% set version = "1.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1cad383034e3f8fb7d2bf8e01c033c9594023d76658127417be84baa0817f106

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-exporter-jaeger-proto-grpc ==1.20.0
    - opentelemetry-exporter-jaeger-thrift ==1.20.0
    - python >=3.6

test:
  imports:
    - src
    - src.opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-jaeger
  summary: Jaeger Exporters for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
